== New features in Mocha Pro 2021 v8.0.0

* *PowerMesh Tracker:* A new tracking option, “Mesh” provides subplanar warp tracking in a layer so you are no longer limited to flat, rigid surfaces. +
  For more information on using the PowerMesh feature, see the <<powermesh, PowerMesh>> section of the Tracking Basics chapter.
* *PowerMesh Export to After Effects Nulls:* You can export PowerMesh tracks to After Effects nulls via the plug-in interface. See <<powermesh_nulls, Creating PowerMesh Nulls>> in the Plug-In section of the User Guide.
* *PowerMesh Export to Alembic:* You can export tracks to a Alembic Mesh with a camera based on the PowerMesh tracking. See the section on <<export_alembic, Exporting to Alembic>> for more details on how to use the format.
* *Mesh Warp Stabilize:* Using the PowerMesh, you can now warp or unwarp the mesh area in the Stabilize module.
    * This option is also available in the plug-in render options so you can easily unwarp an area, modify it, then rewarp with a copy of the original effect.
    * See the <<warp_mapping, Warp Mapping>> section of the stabilize module.
* *AdjustTrack V2:* We’ve completely overhauled AdjustTrack to be easier to use and less prone to errors. For more information on using AdjustTrack V2, see the <<adjust_track, AdjustTrack Module>> chapter.
* *Out of Process Mocha Plug-In:* The Mocha Plug-in now operates as a separate process, which allows far greater resource management and stability.
* *Plug-in Python Support:* Once restricted to Standalone users, you can now run Python scripts in the Mocha Pro plug-in. See the separate Python Guide for more details.
