== New features in Mocha 2020 v7.0.2
* *Silhouette 2020 Support:* The Mocha Pro OFX plugin is now optimised to run in Silhouette 2020
* *Silhouette Shapes Export Support:* The Mocha Pro Plugin now supports Silhouette shape exports to disk (and to clipboard in Silhouette 2020.0.1)
* *Silhouette Corner Pin Export Support:* The Mocha Pro Plugin now exports Silhouette tracking data to disk (and to clipboard in Silhouette 2020.0.1)
* *Silhouette/Mocha Bundle license support:* Bundles of Mocha Pro and Silhouette can now be purchased and activated with a single license key
* *Silhouette 2020 OCIO Support:* Mocha OFX plugins now sync to the Silhouette OCIO color profiles
* *OCIO viewer preferences are now saved:* OCIO viewer preferences are now saved with the project.

== New features in Mocha 2020 v7.0.0
* *Mega Plates Module:* Generate large plates of the whole scene based on tracked planes
* *Area Brush:* Quickly paint areas to turn into splines
* *OCIO Support:* Load OCIO configs directly into Mocha
* *Python 3 Support:* Mocha now uses Python 3.7
* *Updated Python API:* New tools to modify and create keyframes, along with a streamlined parameter system.
