
== Introduction
Welcome to mocha, tracking and rotoscoping tools that make your tracking and rotoscoping work much easier. 

Our tools are based on our proprietary Planar Tracking technology, an awesome approach to 2D tracking which will help you to generate accurate corner-pins and track and transform your roto splines in a powerful way.
	
NOTE: This manual covers all products in the mocha family. Export and interface features may differ between _mocha Pro_ and _mocha Plus, mocha HitFilm or mocha AE_. Legacy applications such as mokey and monet will have significant interface difference to the current versions. Please refer to their offline manuals.

=== The Art of Tracking
Tracking and rotoscoping are part of almost any visual effects project. For 2D tracking, point trackers are most commonly used, but to get good point tracks requires a mix of experience and luck. You often have to &ldquo;prime&rdquo; a clip for optimum tracking using color correctors and other image manipulations. If the point being tracked exits frame, you get into offset tracking, which presents its own set of challenges. If it all fails, you are into hand tracking, which is time consuming and very hard to get accurate.

Mocha is a 2D tracker that requires less experience and luck to be successful with, does not require the image to be primed and is less likely to require a lot of tricks or hand tracking on difficult shots.

=== There Are No Point Trackers
In mocha splines are used for both tracking and rotoscoping. This is a different method from standard 1-point or multi-point tracking tools.

Traditional tracking tools require that you locate &ldquo;points&rdquo; that remain consistent throughout the entire shot in order to track movement. This is itself a difficult task, especially when tracking a shot that was not originally designed to be tracked. If you wish to also track rotation, perspective and shear you need even more clear and consistent points to track.

Traditional roto methodology would have you outline a shape with the minimum number of points necessary then either manually move the control points or track the shape with a point tracker to &ldquo;get it close&rdquo;. Even when using multi-point trackers to impart rotation and scale to the roto spline, the results are often unusable if there is any perspective change during the shot.

Instead, Imagineer's Planar Tracker tracks an object's translation, rotation and scaling data based on the movement of a user-defined plane.
A plane is any flat surface having only two dimensions, such as a table top, a wall, or a television screen. Planes provide much more detail to the computer about an object's translation, rotation and scaling than is possible with point-based tracking tools. Even as an object leaves and enters a frame, there is usually enough information for the Planar Tracker to maintain a solid track of the object.
When you work with the mocha tools, you will need to look for planes in the clip. More specifically, you will need to look for planes that coincide with movements you want to track. If someone is waving goodbye, you can break their arm into two planes - the upper and lower limbs. Although not all of the points on the arm sections actually lie on the same two-dimensional surface, the apparent parallax will be minimal.


=== New features in mocha 4.1.3
*mocha* 4.1.3 is a patch update to include the new *MochaBlend* export formats.

=== New features in mocha 4.1.2
*mocha* 4.1.2 was a patch update to to address some fixes

=== New features in mocha 4.1.1
*mocha* 4.1.1 was a patch update to mainly to address some fixes, but also has:

* *Blackmagic Fusion Tracking Offset:* Fusion tracking data now exports with the frame offset in mocha.
* *Undo/Redo of Point Stepping:* Users can now undo/redo stepping to the next/previous control point

=== New features in mocha 4.1.0 
*mocha* 4.1.0 contains new functionality and format support

New features include:

* *Open Splines:* You can now draw open splines by finishing with Shift + Right Click.  These splines export to After Effects CC 2014 and Nuke
* *EXR 2.0:* Loading a multi-part EXR file will show all the available parts in the streams drop down in the clip tab
* *Export Shapes to Nuke SplineWarp:* We now export to the spline warp node so you don't have to copy splines from Roto nodes to the effect
* *Export shape data to HitFilm 3 Pro:* A new shape format for Hitfilm 3 Pro
* *Save/Load 3D Solves:* You can now save your solved 3d data to the project file
* *Additional 3D Camera Solver Result Improvements:* You can now get more consistently accurate results
* *Next/Previous Control Point Shortcuts:* You can now cycle though spline points using the '{' and '}' keys
* *Python Initialization:* We include an init.py file for running start up scripts.  See the Python User Guide for more details
* *Python Updates:* There are multiple additions to the Python API.  See the Python Reference for more details.

