== New features in Mocha 2019.5
* *Flame 2020 Support:* The Mocha Pro OFX plugin now supports Flame 2020
* *Edge-Snapping:* You can now select points and press the ‘Alt+S’ key to snap those points to the nearest edge, or hold S to drag-snap
* *After Effects CC Power Pin Export:* We now export corner pins to the Power Pin effect
* *Layout Manager:* You can now save, modify and order layouts from the View menu. Any new layouts you create will appear in the workspace drop down
* *Spline and Matte rendering performance improvements:* Projects with many layers or control points now render much faster to screen. Mattes also render much faster.
* *Autosave now has backups:* You can now iterate autosaves to make sure minimal work is lost. Autosaves are no longer removed on exit to the host.


== New features in Mocha 2019
* *GPU Accelerated Remove Module:* The remove module is now GPU supported to speed up renders significantly, including illumination modelling.
* *Improved masking & roto with new spline creation tools:* Adds magnetic spline with edge snapping, freehand spline tool, ellipse, and rectangle tools
* *Redesigned interface:* Mocha Essentials workspace with streamlined user interface: Makes planar tracking easier to learn and master than ever before
* *High resolution screen support:* Interface now supports higher resolution screens
* *Mocha Pro and Mocha VR features are now combined into one product:* Mocha Pro users can utilise all features found in Mocha VR.
